name: "Docs as Code - Confluence"
description: "Publish the content of a folder to confluence"
branding:
  icon: 'book-open'
  color: 'blue'
author: "Bhacaz"
inputs:
  folder:
    description: "Folder containing the documentation to publish."
    required: true
  username:
    description: "Confluence username or email"
    required: true
  password:
    description: "Confluence password or API key"
    required: true
  confluence-base-url:
    description: "Your Confluence url"
    required: true
  space-id:
    description: "Confluence space id to publish the documentation"
    required: true
  parent-page-id:
    description: "Page id under which the documentation will be published"
    required: true
runs:
  using: "node16"
  main: "index.js"
